apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkin-pipeline
  namespace: default
spec:
  project: default
  source:
    repoURL: https://github.com/kumari-31/cicd-2.git
    targetRevision: HEAD
    path: files
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: {}
