apiVersion: v1
kind: Service
metadata:
  name: todo-service
  labels:
    app: to-do-app
    app.kubernetes.io/instance: jenkins-pipeline
spec:
  type: NodePort
  selector:
    app: to-do-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 31000 
