apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: calico-networkpolicy-access
subjects:
- kind: ServiceAccount
  name: example-argocd-argocd-server
  namespace: default
roleRef:
  kind: ClusterRole
  name: calico-networkpolicy-reader
  apiGroup: rbac.authorization.k8s.io
