apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: calico-networkpolicy-reader
rules:
- apiGroups: ["projectcalico.org"]
  resources: ["networkpolicies"]
  verbs: ["get", "list", "watch"]
