apiVersion: apps/v3
kind: Deployment
metadata:
  name: todo-app
  labels:
    app: to-do-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: to-do-app
  template:
    metadata:
      labels:
        app: to-do-app
    spec:
      containers:
      - name: todo-app
        image: kumari3333/cicd-3:39
        ports:
        - containerPort: 8000
